enum ActionType {
  GET_USER_REQUEST = "GET_USER_REQUEST",
  GET_USER_SUCCESS = "GET_USER_SUCCESS",
  GET_USER_FAIL = "GET_USER_FAIL",

  SEARCH_USER_REQUEST = "SEARCH_USER_REQUEST",
  SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS",
  SEARCH_USER_FAIL = "SEARCH_USER_FAIL",
  
  GET_POST_REQUEST = "GET_POST_REQUEST",
  GET_POST_SUCCESS = "GET_POST_SUCCESS",
  GET_POST_FAIL = "GET_POST_FAIL",

  SEARCH_POST_REQUEST = "SEARCH_POST_REQUEST",
  SEARCH_POST_SUCCESS = "SEARCH_POST_SUCCESS",
  SEARCH_POST_FAIL = "SEARCH_POST_FAIL",

  PAGINATION_POST_REQUEST = "PAGINATION_POST_REQUEST",
  PAGINATION_POST_SUCCESS = "PAGINATION_POST_SUCCESS",
  PAGINATION_POST_FAIL = "PAGINATION_POST_FAIL",
  
  ADD_USER = "ADD_USER",
  EDIT_USER = "EDIT_USER",
  DELETE_USER = "DELETE_USER",

  ADD_POST = "ADD_POST",
  EDIT_POST = "EDIT_POST",
  DELETE_POST = "DELETE_POST",
}

export default ActionType;